<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="PC81978" name="pytest" skipped="0" tests="1" time="4.116" timestamp="2021-06-22T07:05:36.971120"><testcase classname="" file="" name="" time="0.000"><error message="collection failure">C:\program files\python37\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1006: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:983: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:967: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:677: in _load_unlocked
    ???
.venv\lib\site-packages\_pytest\assertion\rewrite.py:170: in exec_module
    exec(co, module.__dict__)
tests\application\detr\conftest.py:5: in &lt;module&gt;
    from application.pages.detr.detr import DETRApp
application\pages\__init__.py:2: in &lt;module&gt;
    from application.pages import (
application\pages\holoviews_linked_brushing.py:34: in &lt;module&gt;
    tags=["Panel", "Bokeh", "Plotly", "HoloViews", "Linked Brushing", "Cross Filter"],
E   TypeError: create_application() got an unexpected keyword argument 'description_long'</error></testcase></testsuite></testsuites>